force-app/main/default/objects/B2B_Customer__c/B2B_Customer__c.object-meta.xml
<CustomObject>
    <label>B2B Customer</label>
    <nameField>
        <label>B2B Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2B Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/B2B_Customer__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <label>Company Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/B2B_Customer__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date Business Commenced</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/B2B_Customer__c/fields/DNB_Number__c.field-meta.xml
<CustomField>
    <fullName>DNB_Number__c</fullName>
    <label>DNB Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/B2B_Customer__c/fields/E_mail_Billing__c.field-meta.xml
<CustomField>
    <fullName>E_mail_Billing__c</fullName>
    <label>E-mail-Billing</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/B2B_Customer__c/fields/E_mail_Purchasing__c.field-meta.xml
<CustomField>
    <fullName>E_mail_Purchasing__c</fullName>
    <label>E-mail-Purchasing</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/B2B_Customer__c/fields/Other_Loan__c.field-meta.xml
<CustomField>
    <fullName>Other_Loan__c</fullName>
    <label>Other Loan</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/B2B_Customer__c/fields/Phone1__c.field-meta.xml
<CustomField>
    <fullName>Phone1__c</fullName>
    <label>Phone</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/B2B_Customer__c/fields/Primary_Finance_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Finance_Contact__c</fullName>
    <label>Primary Finance Contact</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/B2B_Customer__c/fields/Tax_I_D_Number__c.field-meta.xml
<CustomField>
    <fullName>Tax_I_D_Number__c</fullName>
    <label>Tax I.D. Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/B2B_Customer__c/fields/Type_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Business__c</fullName>
    <label>Type of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corporation</fullName>
            </value>
            <value>
                <fullName>Non-Corporation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company_Name__c/Company_Name__c.object-meta.xml
<CustomObject>
    <label>Company Name</label>
    <nameField>
        <label>CompanyName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Names</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Company_Name__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <label>Company Name</label>
    <referenceTo>B2B_Customer__c</referenceTo>
    <relationshipLabel>Company Names</relationshipLabel>
    <relationshipName>Company_Names</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/InsertCustomer.cls
public with sharing class InsertCustomer {
    @AuraEnabled
    public static string insertDetails(String name, String cName, Date dateOfBusiness,/* String typeOfBusiness,*/ String primaryFinanceContact, String phone1, String billingEmail,
                                      String purchasingEmail, String bankName, String phone, Integer taxNum, Integer dnbNum) {
        try {

            List<B2B_Customer__c> Details = new List<B2B_Customer__c>();
            B2B_Customer__c newApplication = new B2B_Customer__c();

            newApplication.Name = name;
            //accDetails.LastName=name;
            newApplication.Company_Name__c = cName;
            newApplication.Date__c = dateOfBusiness;
            //newApplication.Type_of_Business__c = typeOfBusiness;
            newApplication.Primary_Finance_Contact__c = primaryFinanceContact;
            newApplication.Phone1__c = phone1;
            newApplication.E_mail_Billing__c = billingEmail;
            newApplication.E_mail_Purchasing__c = purchasingEmail;
            newApplication.Bank_Name__c = bankName;
            newApplication.Phone__c = phone;
            newApplication.Tax_I_D_Number__c = taxNum;
            newApplication.DNB_Number__c = dnbNum;
            //newApplication.Type_of_Business__c = businessType;
           // newApplication.Other_Loan__c = otherLoan;

            Details.add(newApplication);
            insert Details;

            return 'Success';
        } catch (Exception e) {
            System.debug('Failed');
            return 'Failed ' + e.getMessage();
        }
    }
}